exec-once=qs -c noctalia-shell
exec-once=~/.config/mango/performance.sh
# Keep clipboard content after app closes
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0
# Watch clipboard and store history
exec-once=wl-paste --type text --watch cliphist store