allow_tearing=1
syncobj_enable=1
monitorrule=name:eDP-1,width:1920,height:1080,refresh:144,x:0,y:0
monitorrule=name:HDMI-A-1,width:2560,height:1440,refresh:144,x:1920,y:0
source=./e-ink.conf
source=./noctalia-keybinds.conf
source=./autostart.conf
#autostart applications
exec = mmsg -s -l TG
windowrule=force_maximize:1,force_tiled_state:1,force_tearing:1,title:STALCRAFT
# This sources the noctalia theme

source = /home/kuba/.config/mango/noctalia.conf

