#window rules
windowrule=force_maximize:1,ignore_minimize:1,ignore_maximize:1,force_tiled_state:1,force_tearing:1,title:STALCRAFT

blur=0
shadows=0
animations=1
animation_duration_move=150
animation_duration_open=250
animation_duration_tag=100
animation_duration_close=250
animation_duration_focus=10n
blur_optimized=1
