bind=SUPER,T,spawn,foot
bind=SUPER,Q,killclient
bind=SUPER,A,spawn_shell,~/.config/rofi/launcher/launcher.sh
bind=SUPER,Escape,spawn_shell,~/.config/rofi/powermenu/powermenu.sh
bind=SUPER,E,spawn,nemo
bind=SUPER,B,spawn,firefox
bind=SUPER,C,spawn,code
bind=SUPER,r,reload_config
bind=NONE,Print,spawn_shell,grim -l 0 -g "$(slurp)" - | wl-copy
bind=SUPER+SHIFT,w,togglefullscreen
bind=SUPER,w,togglemaximizescreen
bind=SUPER,f,togglefloating
# Switch window focus (Arrow Keys)
bind=SUPER,left,focusdir,left
bind=SUPER,right,focusdir,right
bind=SUPER,up,focusdir,up
bind=SUPER,down,focusdir,down
bind=SUPER,Tab,toggleoverview

# Volume controls
bind=NONE,XF86AudioRaiseVolume,spawn_shell,~/.config/waybar/volup.sh
bind=NONE,XF86AudioLowerVolume,spawn_shell,~/.config/waybar/voldown.sh
bind=NONE,XF86AudioMute,spawn_shell,~/.config/waybar/volmute.sh

# power profile switcher
bind=NONE,XF86Search,spawn_shell,~/.config/waybar/powerprofile.sh

# playerctl controls
bind=NONE,XF86AudioPlay,spawn_shell,playerctl play-pause
bind=NONE,XF86AudioNext,spawn_shell,playerctl next
bind=NONE,XF86AudioPrev,spawn_shell,playerctl previous

# Move/Swap window (SUPER + SHIFT + Arrows)
bind=SUPER+SHIFT,left,exchange_client,left
bind=SUPER+SHIFT,right,exchange_client,right
bind=SUPER+SHIFT,up,exchange_client,up
bind=SUPER+SHIFT,down,exchange_client,down

# Switch Tags (SUPER + 1-9)
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
bind=SUPER,0,view,10,0

# Move window to Tag silently (SUPER + ALT + 1-9)
bind=SUPER+SHIFT,1,tagsilent,1,0
bind=SUPER+SHIFT,2,tagsilent,2,0
bind=SUPER+SHIFT,3,tagsilent,3,0
bind=SUPER+SHIFT,4,tagsilent,4,0
bind=SUPER+SHIFT,5,tagsilent,5,0
bind=SUPER+SHIFT,6,tagsilent,6,0
bind=SUPER+SHIFT,7,tagsilent,7,0
bind=SUPER+SHIFT,8,tagsilent,8,0
bind=SUPER+SHIFT,9,tagsilent,9,0
bind=SUPER+SHIFT,0,tagsilent,10,0

drag_tile_to_tile=1

# SUPER + Left Mouse to Drag, SUPER + Right Mouse to Resize
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
