# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x414868ff
rootcolor = 0x212337ff
bordercolor = 0x606b9dff
focuscolor = 0x37f499ff
maximizescreencolor = 0x04d1f9ff
urgentcolor = 0xf16c75ff
scratchpadcolor = 0xa48cf2ff
globalcolor = 0x00793eff
overlaycolor = 0x00404cff
